// Generated by CoffeeScript 1.6.3
if (typeof define !== 'function' && !define.amd) {
  this.define = function() {
    return this.ribcageSoap || (this.ribcageSoap = {});
  };
}

define(function(require) {
  var SoapCollection, SoapModel, soapMixin;
  soapMixin = require('./lib/mixin');
  SoapModel = require('./lib/model');
  SoapCollection = require('./lib/collection');
  return {
    mixin: soapMixin,
    Model: SoapModel,
    Collection: SoapCollection
  };
});
