// Generated by CoffeeScript 1.6.3
/*!
@author Branko Vukelic <branko@brankovukelic.com>
@license MIT
*/

var _this = this;

if (typeof define !== 'function' || !define.amd) {
  this.require = function(dep) {
    return (function() {
      switch (dep) {
        case 'ribcage':
          return _this.Ribcage;
        case './mixin':
          return _this.ribcageSoap.mixin;
        default:
          return null;
      }
    })() || (function() {
      throw new Error("Unmet dependency " + dep);
    })();
  };
  this.define = function(factory) {
    return _this.ribcageSoap.Collection = factory(_this.require);
  };
}

define(function(require) {
  var SoapCollection, ribcage, soapMixin;
  ribcage = require('ribcage');
  soapMixin = require('./mixin');
  SoapCollection = ribcage.collections.BaseCollection.extend(soapMixin);
  ribcage.collectionMixins.SoapCollection = soapMixin;
  return ribcage.collections.SoapCollection = SoapCollection;
});
